name: MadogCore
schemes:
  MadogCore:
    build:
      targets:
        MadogCore: all
        MadogCoreTests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - MadogCore
      targets:
        - MadogCoreTests
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
targets:
  MadogCore:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: MadogCore/Info.plist
    sources:
      - MadogCore
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MadogCoreTests
    dependencies:
      - target: MadogCore
