name: MadogCore
schemes:
  MadogCore:
    build:
      targets:
        MadogCore: all
    test:
      gatherCoverageData: true
      coverageTargets:
        - MadogCore
      targets:
        - MadogCoreTests
        - MadogCoreKIFTests
  MadogCoreTestUtilities:
    build:
      targets:
        MadogCoreTestUtilities: all
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
    tvOS: "16.0"
packages:
  Provident:
    url: https://github.com/cerihughes/provident
    majorVersion: 6.0.0
  KIF:
    url: https://github.com/kif-framework/KIF
    majorVersion: 3.8.0
targets:
  MadogCore:
    type: framework
    supportedDestinations: [iOS, macOS, tvOS]
    settings:
      INFOPLIST_FILE: MadogCore/Info.plist
    sources:
      - MadogCore
    dependencies:
      - package: Provident
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogCoreTestUtilities:
    type: framework
    supportedDestinations: [iOS, tvOS]
    settings:
      INFOPLIST_FILE: MadogCoreTestUtilities/Info.plist
    sources:
      - MadogCoreTestUtilities
    dependencies:
      - target: MadogCore
      - package: KIF
        destinationFilters: [iOS]
      - sdk: XCTest.framework
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogCoreTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS, tvOS]
    sources:
      - MadogCoreTests
    dependencies:
      - target: MadogCore
  MadogCoreKIFTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, tvOS]
    settings:
      TEST_TARGET_NAME: TestApp
    sources:
      - MadogCoreKIFTests
    dependencies:
      - target: MadogCore
      - target: MadogCoreTestUtilities
      - target: TestApp
      - package: KIF
        destinationFilters: [iOS]
  TestApp:
    type: application
    supportedDestinations: [iOS, tvOS]
    settings:
      INFOPLIST_FILE: TestApp/Info.plist
    sources: TestApp
