name: MadogCore
schemes:
  MadogCore:
    build:
      targets:
        MadogCore: all
        MadogCoreTests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - MadogCore
      targets:
        - MadogCoreTests
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
    macOS: "13.0"
    tvOS: "16.0"
packages:
  Provident:
    url: https://github.com/cerihughes/provident
    majorVersion: 6.0.0
targets:
  MadogCore:
    type: framework
    supportedDestinations: [iOS, macOS, tvOS]
    settings:
      INFOPLIST_FILE: MadogCore/Info.plist
    sources:
      - MadogCore
    dependencies:
      - package: Provident
    postCompileScripts:
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  MadogCoreTests:
    type: bundle.unit-test
    supportedDestinations: [iOS, macOS, tvOS]
    sources:
      - MadogCoreTests
    dependencies:
      - target: MadogCore
